language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - libfftw3-dev
      # libuhd-dev is not allowed

compiler:
  - clang

script:
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure --disable-zeromq --disable-output-uhd
    make
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure --disable-output-uhd
    make

